#!/bin/bash
cd /opt/bitnami/apps/magento/htdocs
cat /var/log/syslog | grep -oP "(?<=password to ').*(?=')" | awk '{print "App Password: "$1}' 

# Set permissions
sudo sed "s/<public-key>/$PUBLIC_KEY/g" -i auth.json.sample
sudo sed "s/<private-key>/$PRIVATE_KEY/g" -i auth.json.sample
sudo cp auth.json.sample auth.json  
sudo composer require cloudinary/cloudinary:$PLUGIN_VERSION
echo Installed cloudinary/cloudinary:"$PLUGIN_VERSION" 

# Enable
sudo ./bin/magento-cli module:enable Cloudinary_Cloudinary --clear-static-content
echo Enabled plugin 

# Refresh
sudo ./bin/magento-cli setup:upgrade
sudo ./bin/magento-cli setup:di:compile
sudo ./bin/magento-cli setup:static-content:deploy
sudo ./bin/magento-cli cache:clean
sudo ./bin/magento-cli cache:flush	
echo Refreshed, Compiled and cleaned Cache
